name: Deploy to Production

on:
  push:
    branches:
      - Testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        id: jest_tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy to Production
        id: deployment
        uses: actions/deploy-pages@v4
